# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34a4355c9b551f769a637f765e0797e717c9f245b9c8df63903c331ecbb64f7b8a1e2a5b964ee7a4692fb304f141a7da410554d94a8949303674ad80146d5dd7

test:
  secret_key_base: 35d55e74a09ab734226d31026e07fc7bd21f33b5e7aef3986dcc8144b81c79e209e516695a9ee8a6cd6e2c9a9494c18bb0c6109c076fcc54d848cdc0097d4319

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
